
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=64
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=512

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_GPIO=y

# 네트워킹 기본 활성화
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y

CONFIG_POSIX_API=y
CONFIG_ZVFS_OPEN_MAX=12


CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_WIFI_MGMT=y

# ESP32 Wi-Fi 하드웨어 드라이버 활성화
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y

# IP 스택 및 DHCPv4 활성화 (접속 후 IP를 자동으로 받기 위함)
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y

# 내부 관리 네트워킹 레이어 활성화
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_STACK_SIZE=2048

# 로그 출력 활성화 (디버깅용)
CONFIG_NET_LOG=y
# CONFIG_WIFI_LOG_LEVEL_DBG=y

# 영구 저장공간 설정 (Settings 서브시스템) 활성화
CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y

# 저장소 백엔드로 임베디드용 비휘발성 파일 시스템(NVS) 지정
CONFIG_SETTINGS_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

# 시스템 재부팅(Reboot) API 활성화
CONFIG_REBOOT=y

# SNTP 네트워크 시간 보정 프로토콜 활성화
CONFIG_SNTP=y
CONFIG_POSIX_API=y

# DNS 도메인 해석이 필요한 경우 (time.google.com 주소 파싱용)
CONFIG_DNS_RESOLVER=y